### ISSUE TITLE
flashlight and qr-code scanning from website

### ISSUE THREAD

**Issue by Nimuedaertya** [Nimuedaertya/reallife-quest-murder-game#6]
Being able to use the flashlight and a qr-code scanner from the website

**Comment by Nimuedaertya** [comment]
Suggestion: https://github.com/nimiq/qr-scanner

**Comment by CyberDev01** [comment]
QR-Code-Scanner is working in Brave and Firefox on both Desktop-Browsers and Smartphone-Browsers.

The button for using the flashlight doesn't appear in on Desktop-Browsers and in Smartphone-Firefox but in Smartphone-Brave. Unfortunately it's not working with my Phone "Google Pixel 8 Pro" as the flashlight is is not beeing activated.
